// GroupScreen.js
import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  Image,
  TextInput,
  Alert,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  StatusBar,
  Modal
} from 'react-native';
// Firebase imports:
import {
  getFirestore,
  collection,
  query,
  where,
  onSnapshot,
  doc,
  updateDoc,
  arrayUnion,
  setDoc,
  serverTimestamp,
  getDocs
} from 'firebase/firestore';
import { app } from '../firebaseConfig';
import ArrowsIcon from '../assets/arrowsiconupdated.png';

const db = getFirestore(app);

function randomSixDigit() {
  return String(Math.floor(100000 + Math.random() * 900000));
}

const GroupScreen = ({ navigation, route }) => {
  const { username } = route.params || {};

  const [userGroups, setUserGroups] = useState([]);
  const [groupName, setGroupName] = useState('');
  const [joinCode, setJoinCode] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [showJoinModal, setShowJoinModal] = useState(false);
  const [showCreateModal, setShowCreateModal] = useState(false);

  // fetch only groups you belong to
  useEffect(() => {
    if (!username) return;
    const q = query(
      collection(db, 'groups'),
      where('members', 'array-contains', username.toLowerCase())
    );
    const unsub = onSnapshot(
      q,
      (snap) => {
        const arr = [];
        snap.forEach((d) => {
          arr.push({ id: d.id, ...d.data() });
        });
        // sort by lastAccessed descending
        arr.sort(
          (a, b) => (b.lastAccessed?.seconds || 0) - (a.lastAccessed?.seconds || 0)
        );
        setUserGroups(arr);
      },
      (e) => setErrorMessage(e.message)
    );
    return unsub;
  }, [username]);

  // create a new group with autogenerated code
  const createGroupFirestore = async (newGroupName, user) => {
    const code = randomSixDigit();
    const groupRef = doc(db, 'groups', newGroupName);
    await setDoc(groupRef, {
      creator: user.toLowerCase(),
      members: [user.toLowerCase()],
      createdAt: serverTimestamp(),
      code,
      lastAccessed: serverTimestamp()
    });
  };

  // join existing group by 6‑digit code only
  const joinGroupByCode = async (code) => {
    const groupsRef = collection(db, 'groups');
    const q = query(groupsRef, where('code', '==', code));
    const snaps = await getDocs(q);
    if (snaps.empty) {
      Alert.alert('Error', 'Invalid group code.');
      return;
    }
    // take first matching group
    const groupSnap = snaps.docs[0];
    await updateDoc(groupSnap.ref, {
      members: arrayUnion(username.toLowerCase()),
      lastAccessed: serverTimestamp()
    });
    navigation.navigate('EventScreen', {
      username,
      groupName: groupSnap.id
    });
  };

  // handlers
  const onCreateModalSubmit = () => {
    if (!groupName.trim()) {
      return Alert.alert('Error', 'Please enter a group name.');
    }
    createGroupFirestore(groupName.trim(), username)
      .then(() => setShowCreateModal(false))
      .catch((e) => setErrorMessage(e.message));
    setGroupName('');
  };

  const onJoinModalSubmit = () => {
    if (!joinCode.trim() || joinCode.trim().length !== 6) {
      return Alert.alert('Error', 'Please enter the 6‑digit code.');
    }
    joinGroupByCode(joinCode.trim())
      .then(() => setShowJoinModal(false))
      .catch((e) => setErrorMessage(e.message));
    setJoinCode('');
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
      <StatusBar barStyle="dark-content" />
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.container}
      >
        <View style={styles.topSection}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Image source={ArrowsIcon} style={styles.logoImage} />
          </TouchableOpacity>
          <View style={styles.verticalButtonContainer}>
            <TouchableOpacity
              style={styles.verticalButton}
              onPress={() => setShowJoinModal(true)}
            >
              <Text style={styles.buttonText}>JOIN</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.verticalButton}
              onPress={() => setShowCreateModal(true)}
            >
              <Text style={styles.buttonText}>CREATE</Text>
            </TouchableOpacity>
          </View>
        </View>

        <ScrollView contentContainerStyle={styles.scrollContainer}>
          {errorMessage ? <Text style={styles.errorText}>{errorMessage}</Text> : null}
          {userGroups.length > 0 ? (
            userGroups.map((g) => (
              <View key={g.id} style={styles.groupCard}>
                <View style={styles.groupCardHeader}>
                  <Text style={styles.groupNameText}>{g.id}</Text>
                  <TouchableOpacity
                    onPress={() => {
                      navigation.navigate('EventScreen', {
                        username,
                        groupName: g.id
                      });
                      // bump lastAccessed
                      setTimeout(() => {
                        updateDoc(doc(db, 'groups', g.id), {
                          lastAccessed: serverTimestamp()
                        });
                      }, 1000);
                    }}
                    style={styles.actionButton}
                  >
                    <Text style={styles.actionButtonText}>Go to Group</Text>
                  </TouchableOpacity>
                </View>
              </View>
            ))
          ) : (
            <Text style={styles.noGroupsText}>No groups yet.</Text>
          )}
        </ScrollView>

        {/* Join Modal */}
        <Modal visible={showJoinModal} transparent animationType="slide">
          <View style={styles.modalBackground}>
            <View style={styles.modalContainer}>
              <Text style={styles.modalTitle}>Enter 6‑digit Code</Text>
              <TextInput
                style={styles.modalInput}
                placeholder="123456"
                value={joinCode}
                onChangeText={setJoinCode}
                keyboardType="number-pad"
                maxLength={6}
              />
              <TouchableOpacity style={styles.modalButton} onPress={onJoinModalSubmit}>
                <Text style={styles.buttonText}>JOIN</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.modalButton, styles.modalCancelButton]}
                onPress={() => setShowJoinModal(false)}
              >
                <Text style={styles.buttonText}>Cancel</Text>
              </TouchableOpacity>
            </View>
          </View>
        </Modal>

        {/* Create Modal */}
        <Modal visible={showCreateModal} transparent animationType="slide">
          <View style={styles.modalBackground}>
            <View style={styles.modalContainer}>
              <Text style={styles.modalTitle}>Create Group</Text>
              <TextInput
                style={styles.modalInput}
                placeholder="Group Name"
                value={groupName}
                onChangeText={setGroupName}
                autoCapitalize="none"
                maxLength={20}
              />
              <TouchableOpacity style={styles.modalButton} onPress={onCreateModalSubmit}>
                <Text style={styles.buttonText}>CREATE</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.modalButton, styles.modalCancelButton]}
                onPress={() => setShowCreateModal(false)}
              >
                <Text style={styles.buttonText}>Cancel</Text>
              </TouchableOpacity>
            </View>
          </View>
        </Modal>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF'
  },
  topSection: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#FFFFFF',
    justifyContent: 'flex-start'
  },
  logoImage: {
    width: 75,
    height: 75,
    marginRight: 15
  },
  verticalButtonContainer: {
    justifyContent: 'space-between',
    height: 100
  },
  verticalButton: {
    backgroundColor: '#000000',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: 'center'
  },
  buttonText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#FFFFFF'
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 90
  },
  groupCard: {
    marginBottom: 15,
    padding: 15,
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 10,
    backgroundColor: '#F5F5F5'
  },
  groupCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  groupNameText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000'
  },
  actionButton: {
    backgroundColor: '#000000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF'
  },
  noGroupsText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginTop: 20
  },
  errorText: {
    color: '#FF0000',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)'
  },
  modalContainer: {
    width: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 20
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center'
  },
  modalInput: {
    width: '100%',
    padding: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    color: '#000000',
    fontSize: 16
  },
  modalButton: {
    backgroundColor: '#000000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    marginTop: 5
  },
  modalCancelButton: {
    backgroundColor: '#aaa'
  }
});

export default GroupScreen;


